[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "verystable"
version = "25.99.0-dev"
dependencies = [
    'importlib-metadata; python_version<"3.11"',
]
